services:
  db-backend-rw:
    image: "postgres:16"
    ports:
      - 5432:5432
    volumes:
      - ./docker/pginit:/docker-entrypoint-initdb.d/:ro
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app