apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-backend
  namespace: default
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: db-backend
      dataChecksums: true
  storage:
    size: 10Gi