apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/agares/backend:main-1692449606 # {"$imagepolicy": "flux-system:apps-backend"}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secret-db-backend-app
              readOnly: true
              mountPath: /etc/secrets/db-backend-app
      volumes:
        - name: secret-db-backend-app
          secret:
            secretName: db-backend-app
        - name: secret-db-backend-superuser
          secret:
            secretName: db-backend-superuser
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
