apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/agares/backend:main-1693938861 # {"$imagepolicy": "flux-system:apps-backend"}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secret-db-backend-app
              readOnly: true
              mountPath: /etc/secrets/db-backend-app
          resources:
            limits:
              cpu: '50m'
              memory: 256M
          env:
            - name: HONEYCOMB_KEY
              valueFrom:
                secretKeyRef:
                  name: "honeycomb-key"
                  key: "HONEYCOMB_KEY"
            - name: RUST_BACKTRACE
              value: "1"
      initContainers:
        - name: apps-backend-migrations
          image: ghcr.io/agares/backend-migrations:main-1693937706 # {"$imagepolicy": "flux-system:apps-backend-migrations"}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secret-db-backend-superuser
              readOnly: true
              mountPath: /etc/secrets/db-backend-superuser
      volumes:
        - name: secret-db-backend-app
          secret:
            secretName: db-backend-app
        - name: secret-db-backend-superuser
          secret:
            secretName: db-backend-superuser
        - name: secret-honeycomb-key
          secret:
            secretName: honeycomb-key
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
