---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: apps-backend
  namespace: flux-system
spec:
  image: ghcr.io/agares/backend
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: apps-backend-migrations
  namespace: flux-system
spec:
  image: ghcr.io/agares/backend-migrations
  interval: 1m0s

