apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: apps-backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: apps-backend
  filterTags:
    pattern: '^main-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: apps-backend-migrations
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: apps-backend-migrations
  filterTags:
    pattern: '^main-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc