name: Build docker images
on:
  push:
    paths:
      - apps/backend/**
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v12
        with:
          name: ramona-stuff
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Generate docker image tag
        run: echo image_tag=${GITHUB_REF##*/}-$(date +%s) >> "$GITHUB_ENV"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run checks
        run: nix flake check

      - name: Build backend docker image
        run: "./docker-build.sh backend  \"${{ env.REGISTRY }}/ramonacat/backend:${{ env.image_tag }}\""

      - name: Build backend-migrations docker image
        run: "./docker-build.sh backend-migrations  \"${{ env.REGISTRY }}/ramonacat/backend-migrations:${{ env.image_tag }}\""

      - name: Print image tag
        run: echo ${{ env.image_tag }}

      - name: Publish backend docker image
        run: docker push "${{ env.REGISTRY }}/ramonacat/backend:${{ env.image_tag }}"

      - name: Publish backend-migrations docker image
        run: docker push "${{ env.REGISTRY }}/ramonacat/backend-migrations:${{ env.image_tag }}"